### ISSUE TITLE
riboVIEW not available for R version 3.6.1

### ISSUE THREAD

**Issue by AlexFryd** [carinelegrand/RiboVIEW#1]
Hello!

I would like to test your tool, as it seems really fitting to interpret my ribosome profiling data!

I got the earliest issue possible as I get this warning message when I am trying to install the package:

>  install.packages("RiboVIEW")
Warning message:
package 'RiboVIEW' is not available (for R version 3.6.1)

> 

Is it not a bit odd?

Thanks a lot!
Alex

**Comment by carinelegrand** [comment]
Hi Alex,
Thanks for your note. It should work fine for R version 3.6.1, using the following commands, in R :
> install.packages("devtools")
> library(devtools)
> install_github("carinelegrand/RiboVIEW")

Best,
Carine
