### ISSUE TITLE
Reference CDS annotation format

### ISSUE THREAD

**Issue by Jeff-Gui** [carinelegrand/RiboVIEW#2]
Hi, I don't quite understand the reference CDS annotation format in the vignette. For human genome, where shall I put the chromosome id in the table? Thanks.

**Comment by pspealman** [comment]
@Jeff-Gui 
Not sure if this is helpful to you but a quick check of the CDS and fasta files finds that each ID name in the CDS file (ie, "synth.tsv") corresponds to an entry in the fasta file ("synth.fasta"). 

I suspect that chromosomes are not part of the coordinate system as everything is relative to the transcript (such that sequence before the localStart nucleotide is 5'UTR or transcript leader, with the localStart marking the Start codon). 

As long as you have unique identifiers for your genes/transcripts this should work fine.

**Comment by carinelegrand** [comment]
Hi Jeff, 

like pspealman mentioned, if you have unique mRNA identifiers, RiboVIEW will work fine. 

However I understand your concern : chromosome ID, gene ID, etc. can be important for analysis later on. If you want to keep this information, you could include it in your mRNA ID : 
For instance, replace the "mRNA2" ID by "Chr14_gene1_mRNA2". 

I hope this helps, 

Carine
